version: "3.8"

services:
  db:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    env_file:
      # TODO: Use .env.development.
      - .env.template
    command: uvicorn secure_share.asgi:application --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  client:
    build:
      context: ./client
      args:
        - VITE_API_URL=http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      - server
