# Generated by Django 5.1.4 on 2025-01-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileshare',
            old_name='can_write',
            new_name='can_download',
        ),
    ]
