# Generated by Django 5.1.4 on 2025-01-15 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_rename_fileshare_filepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepermission',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='files.file'),
        ),
    ]
